# name='sangeetha'
# print(f" hell\'o \' {name}")


# lsit1=['hello','world',123]
# lsit1.pop(0)
# print(lsit1)


# if(True):
#     i=1
#     while i>0:
#         i+=1
#         print("loop")

# for i in range(1,11):
#     print("33*",i,"=",33*i)

# set1={1,2,3}
# set2={3,4,5}
# print(set1+set2)

def animal_function():
    animal_name="Cat"
    animal_name="dog"
    print(animal_name)

animal_funcation()

